/**
 * EcoSched — Thermal-Aware Scheduling Module
 * Simulates CPU thermal behavior using RC thermal model
 * T(t) = T_ambient + (T_max - T_ambient) * (1 - e^(-t/τ)) * util_factor
 */

class ThermalController {
  constructor(maxTemp = 80) {
    this.maxTemp     = maxTemp;       // Throttle threshold (°C)
    this.temp        = 30;            // Current temperature
    this.ambientTemp = 30;            // Ambient (°C)
    this.tauHeat     = 40;            // Thermal time constant heating (ms)
    this.tauCool     = 80;            // Thermal time constant cooling (ms)
    this.throttleThreshold = maxTemp;
    this.criticalTemp      = maxTemp + 10;

    // Freq-to-TDP map (Watts)
    this.freqTDP = {
      0.8: 4,   1.2: 8,  1.8: 14,
      2.4: 24,  3.2: 40
    };

    this.history = [];
  }

  /**
   * Update temperature based on CPU activity
   * Uses simplified RC thermal model
   * ΔT = (TDP_power * util - cooling_factor) * dt / thermal_capacitance
   */
  update(util, freq, dtMs) {
    const tdp = this._getTDP(freq);

    // Heat generated by CPU (W * time)
    const heatGen = tdp * util * (dtMs / 1000);

    // Cooling: Newton's law — proportional to temp differential
    const tempDiff   = this.temp - this.ambientTemp;
    const coolingRate= 0.15;  // °C per ms per degree differential
    const heatLost   = tempDiff * coolingRate * dtMs;

    // Thermal capacitance (J/°C) — determines how fast temp changes
    const thermalCap = 2.5;

    const deltaT = (heatGen - heatLost) / thermalCap;
    this.temp = Math.max(this.ambientTemp, Math.min(this.criticalTemp + 5, this.temp + deltaT));

    this.history.push({ temp: this.temp, util, freq });
    return this.temp;
  }

  _getTDP(freq) {
    // Linear interpolation between discrete steps
    const freqs = [0.8, 1.2, 1.8, 2.4, 3.2];
    const tdps  = [4,   8,   14,  24,  40 ];
    for (let i = 0; i < freqs.length - 1; i++) {
      if (freq >= freqs[i] && freq <= freqs[i+1]) {
        const t = (freq - freqs[i]) / (freqs[i+1] - freqs[i]);
        return tdps[i] + t * (tdps[i+1] - tdps[i]);
      }
    }
    return tdps[tdps.length - 1];
  }

  get isThrottling() {
    return this.temp >= this.throttleThreshold;
  }

  get isCritical() {
    return this.temp >= this.criticalTemp;
  }

  get thermalState() {
    if (this.temp < 50)                   return { label: 'Cool',     color: '#00f5c4' };
    if (this.temp < this.maxTemp * 0.75)  return { label: 'Normal',   color: '#10b981' };
    if (this.temp < this.maxTemp * 0.90)  return { label: 'Warm',     color: '#f59e0b' };
    if (this.temp < this.maxTemp)         return { label: 'Hot',      color: '#f97316' };
    return                                       { label: 'THROTTLE', color: '#ef4444' };
  }

  /**
   * Calculate how much freq should be reduced for thermal management
   * Returns multiplier 0.0–1.0
   */
  thermalMultiplier() {
    if (!this.isThrottling) return 1.0;
    const overshoot = this.temp - this.throttleThreshold;
    return Math.max(0.25, 1.0 - overshoot / 20);
  }

  get arcPercent() {
    // 0–100% for temperature arc visualization
    return Math.min(100, Math.max(0, (this.temp - this.ambientTemp) / (this.criticalTemp - this.ambientTemp) * 100));
  }

  get arcColor() {
    const p = this.arcPercent;
    if (p < 40)  return '#00f5c4';
    if (p < 65)  return '#10b981';
    if (p < 80)  return '#f59e0b';
    if (p < 90)  return '#f97316';
    return              '#ef4444';
  }
}

window.ThermalController = ThermalController;
